### ISSUE TITLE
Glossary View results in being thrown back to login page (user not authorized)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-ui#575]
* Setup egeria lab environment (k8s, lab chart, configure/data catalog notebooks)

When clicking on the glossary icon, the page is immediately cleared and the user is bounced back to the UI login panel
Clicking 'back' results in being returned to a glossary page

<img width="299" alt="Screenshot 2023-03-29 at 12 26 51" src="https://user-images.githubusercontent.com/7292002/228522139-be4fb1af-e2c1-41d5-8c39-17d0b6f7b7a4.png">

In my case, the root cause was permissions - the following was found in the ui chassis log
```
2023-03-29 11:33:23.580 -ERROR 1 --- [io-8443-exec-10] o.o.o.u.u.s.a.ExceptionHandlerController : 401 User is not authorized

org.odpi.openmetadata.userinterface.uichassis.springboot.api.exceptions.UserNotAuthorizedException: 401 User is not authorized
	at org.odpi.openmetadata.userinterface.uichassis.springboot.api.SecureController.getUser(SecureController.java:38) ~[classes!/:na]
	at org.odpi.openmetadata.userinterface.uichassis.springboot.api.glossary.GlossaryViewController.getAllGlossaries(GlossaryViewController.java:51) ~[classes!/:na
```
The same occurs with other users, including garygeeke

Error handling is needed for this case

Original report: https://github.com/odpi/egeria-ui/issues/480

**Comment by sarbull** [comment]
fixed by this https://github.com/odpi/egeria/pull/7609
